<?php

namespace App\Enums;
enum Grade: string
{
    // case 1A = '1A';
    // case 1A+ = '1A+';
    // case 1B = '1B';
    // case 1B+ = '1B+';
    // case 1C = '1C';
    // case 1C+ = '1C+';
    // case 2A = '2A';
    // case 2A+ = '2A+';
    // case 2B = '2B';
    // case 2B+ = '2B+';
    // case 2C = '2C';
    // case 2C+ = '2C+';
    // case 3A = '3A';
    // case 3A+ = '3A+';
    // case 3B = '3B';
    // case 3B+ = '3B+';
    // case 3C = '3C';
    // case 3C+ = '3C+';
    // case 4A = '4A';
    // case 4A+ = '4A+';
    // case 4B = '4B';
    // case 4B+ = '4B+';
    // case 4C = '4C';
    // case 4C+ = '4C+';
    // case 5A = '5A';
    // case 5A+ = '5A+';
    // case 5B = '5B';
    // case 5B+ = '5B+';
    // case 5C = '5C';
    // case 5C+ = '5C+';
    // case 6A = '6A';
    // case 6A+ = '6A+';
    // case 6B = '6B';
    // case 6B+ = '6B+';
    // case 6C = '6C';
    // case 6C+ = '6C+';
    // case 7A = '7A';
    // case 7A+ = '7A+';
    // case 7B = '7B';
    // case 7B+ = '7B+';
    // case 7C = '7C';
    // case 7C+ = '7C+';
    // case 8A = '8A';
    // case 8A+ = '8A+';
    // case 8B = '8B';
    // case 8B+ = '8B+';
    // case 8C = '8C';
    // case 8C+ = '8C+';
    // case 9A = '9A';
    // case 9A+ = '9A+';
    // case 9B = '9B';
    // case 9B+ = '9B+';
    // case 9C = '9C';
    // case 9C+ = '9C+';
}